### ISSUE TITLE
Docker Installation Failed

### ISSUE THREAD

**Issue by HenryHengZJ** [ewfian/faiss-node#12]
**Describe the bug**
When installing on Docker, following issue exists:
```
404 https://github.com/ewfian/faiss-node/releases/download/v0.2.0/faiss-node-v0.2.0-napi-v8-linuxmusl-x64.tar.gz
```
Seems like the library doesn't support `linuxmusl`? As I couldnt find the `tar.gz` file in releases

**Environment:**
 - Operating system: Docker node:18-alpine
 - Package Version: [e.g. v0.2.0]

**To Reproduce**
1. Init a project with faiss-node installed
2. Build a docker image on the project

**Expected behavior**
Works fine

**Screenshots**
![image](https://github.com/ewfian/faiss-node/assets/26460777/2d585bc1-1c0e-4f94-9146-4b0bf8696f3a)

**Comment by ewfian** [comment]
@HenryHengZJ  Thank you for reporting the issue. It can be reproduced here. I'm going to find a solution next.

**Comment by HenryHengZJ** [comment]
hey @ewfian, can you also add support for arm64? 

when I try to build docker image for arm64 the errors are shown as below:
```
#0 360.7 npm ERR! prebuild-install http request GET https://github.com/ewfian/faiss-node/releases/download/v0.2.1/faiss-node-v0.2.1-napi-v8-linuxmusl-arm64.tar.gz
#0 360.7 npm ERR! prebuild-install http request GET https://github.com/ewfian/faiss-node/releases/download/v0.2.1/faiss-#0 360.7 npm ERR! prebuild-install http request GET https://github.com/ewfian/faiss-node/releases/#0 360.7 npm ERR! prebuild-install http request GET https://github.com/ewfian/faiss-node/releases/download/v0.2.1/faiss-node-v0.2.1-napi-v8-linuxmusl-arm64.tar.gz
#0 360.7 npm ERR! prebuild-install http 404 https://github.com/ewfian/faiss-node/releases/download/v0.2.1/faiss-node-v0.2.1-napi-v8-linuxmusl-arm64.tar.gz
#0 360.7 npm ERR! prebuild-install warn install No prebuilt binaries found (target=8 runtime=napi arch=arm64 libc=musl platform=linux)
#0 360.7 npm ERR! sh: cmake-js: not found
```

Here's the command I use inside [docker folder of Flowise](https://github.com/FlowiseAI/Flowise/tree/main/docker):
1. `docker buildx use mybuilder`
2. `docker buildx build --platform linux/amd64,linux/arm64 --no-cache -t flowiseai/flowise:latest --push .`
