### ISSUE TITLE
Possible to reduce node package size?

### ISSUE THREAD

**Issue by dmb0058** [ewfian/faiss-node#26]
**Describe the bug**
AWS Lambda functions are restricted to 250Mb including layers. Packaging the aws-sdk, faiss-node, fs, langchain, openai and adm-zip blows the limit.

I've pulled out only the aws sub-packages I need (s3 and secrets-manager) and the fs and adm-zip packages are tiny, but faiss-node is pretty big. I see it has Readme files and stuff, so I guess it's not 'minimal' - any chance of a slimmed down npm package?

**Environment:**
 - Operating system: AWS Lambda
 - Nodejs Version: v18.x
 - Package Version: latest

**To Reproduce**
1. Zip the nodejs/node_modules hierarchy
2. Attempt to create a Lambda layer
3. Error is "Layer max. size is 250Mb" (paraphrased)

**Expected behavior**
The layer is correctly created.

**Comment by ewfian** [comment]
@dmb0058  Now use `MKL` on linux and  `openblas` on musllinux.
We can consider replacing it with `openblas` for reducing size.

![image](https://github.com/ewfian/faiss-node/assets/12423122/7ba8f9a2-08fd-4d14-96d2-172ca33346fc)

**Comment by dmb0058** [comment]
Excellent news! This will make a lot of difference, thanks.

I'll happily try this once the langchainjs issue is resolved.

**Comment by ewfian** [comment]
@dmb0058 I will publish a new version to npm soon.

**Comment by ewfian** [comment]
@dmb0058 The new version v0.2.3 was released.

**Comment by dmb0058** [comment]
That's great news, thanks for all your help :)
