### ISSUE TITLE
[AWS]Any chance of an arm64 build of the Node.js layer

### ISSUE THREAD

**Issue by dmb0058** [ewfian/faiss-node#36]
Hi,

Just wondering if an arm64 build could be available as well as the x86_64 one?

I'd like to keep the runtime costs down, and arm64 is cheap :)

Thanks,

David

**Comment by ewfian** [comment]
We do have arm64 pre-builds
<img width="880" alt="image" src="https://github.com/ewfian/faiss-node/assets/12423122/2e38607b-f14d-4d7b-927d-38085e9b5285">

**Comment by ewfian** [comment]
Sorry, it just occurred to me that I might have misunderstood you, you actually wanted arm64 build for **AWS**?

**Comment by dmb0058** [comment]
Hi,

Sorry, yes, for AWS. I should have been clearer :)

David

**Comment by dmb0058** [comment]
In case it helps anyone, when I attached the faiss x86_64  layer to a lambda built for the arm64 architecture I got a rather strange error message. Re-building the lambda as x86_64 fixed the problem and it all worked

Could not import faiss-node. Please install faiss-node as a dependency with, e.g. `npm install -S faiss-node`.

/opt/nodejs/node_modules/faiss-node/build/Release/faiss-node.node: cannot open shared object file: No such file or directory
